MAKEFLAGS = -sR
MAKE = make
CD = cd
CP = cp

BUILD_PATH = ./build/
INITLDR_PATH =./initldr/

# 根据 script 中的 .S 预先生成中间 makefile 文件
PREMENTMFLGS = -C $(BUILD_PATH) -f pretreatment.mkf
HALYMFLGS = -C $(BUILD_PATH) -f hal.mk
KRNLMFLGS = -C $(BUILD_PATH) -f krl.mk
DRIVMFLGS = -C $(BUILD_PATH) -f drv.mk
LIBSMFLGS = -C $(BUILD_PATH) -f lib.mk
TASKMFLGS = -C $(BUILD_PATH) -f task.mk
LINKMFLGS = -C $(BUILD_PATH) -f link.mk

build: all

all:
	$(CP) ./script/pretreatment.mkf $(BUILD_PATH)pretreatment.mkf
	$(MAKE) $(PREMENTMFLGS)
	$(CD) $(INITLDR_PATH) && $(MAKE)
	$(MAKE) $(HALYMFLGS)
	$(MAKE) $(KRNLMFLGS)
	$(MAKE) $(LINKMFLGS)
	@echo "build x86 done"